version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "apigw-proxy-dynamodb-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12duhohli7hlx"
s3_prefix = "apigw-proxy-dynamodb-example"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
