AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: di-ipv-dca-spikes APIGW->DynamoDB:GetItem spike

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: API
          Value: !Sub ${AWS::StackName}-di-ipv-dca-spikes
      TimeToLiveSpecification:
        AttributeName: expiry
        Enabled: true

